apiVersion: v1
kind: ConfigMap
metadata:
  name: menu-config
data:
  menu.json: |
    {
      "pizzas": [
        { "id": 1, "name": "Margherita", "toppings": ["tomato", "mozzarella", "basil"], "price": 12.50 },
        { "id": 2, "name": "Pepperoni", "toppings": ["tomato", "mozzarella", "pepperoni"], "price": 15.00 },
        { "id": 3, "name": "Hawaiian", "toppings": ["tomato", "mozzarella", "ham", "pineapple"], "price": 14.75 }
      ],
      "specials": [
        { "name": "The KubePizza Special", "description": "A new daily special" }
      ]
    }